# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvjpWfRn_KcfyfwU1-clCBPAxSx21aNb
"""

a = int(input("いくつまで数えますか"))

i=0

for i in range(1,a+1,1):
    if i % 3 == 0 and i % 5 == 0:
        print(i)
    elif i % 5 == 0:
        print("Buzz")
    elif i % 3 == 0:
        print("Fizz")
    else:
        print(i)